name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Copy files to the server
      uses: appleboy/scp-action@v0.1.7
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "/home/${{ secrets.USERNAME }}/digital_marmot/lucamatei.xyz-temp"

    - name: Setup and Run Website
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: ${{ secrets.PORT }}
        script: |
          rm -rf /home/${{ secrets.USERNAME }}/digital_marmot/lucamatei.xyz
          mv /home/${{ secrets.USERNAME }}/digital_marmot/lucamatei.xyz-temp /home/${{ secrets.USERNAME }}/digital_marmot/lucamatei.xyz
          
          cd /home/${{ secrets.USERNAME }}/digital_marmot/lucamatei.xyz

          yarn install
          yarn build

          sudo systemctl restart lucamatei.xyz